language: ruby
os: linux
dist: bionic
before_install:
    - gem install bundler:2.1.2
cache: bundler

services:
  - postgresql

jobs:
  include:
    - stage: Linter
      script: "bundle exec rubocop"
    - stage: Tests
      script:
        - bundle exec rails db:create
        - bundle exec rails db:migrate
        - bundle exec rspec
